<?php
// Inicializa a sessão se ainda não estiver
if(!isset($_SESSION)) session_start();

// Pega o usuário logado (ou null)
$currentUser = \App\Services\Auth::user();
?>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adota Paraná</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
         min-height: 100vh;
         width: 100%;
         margin: 0px;
         padding: 0px;
        }
        .container_body {
            display: flex;
            position: relative;
        }
        .register_btn {
            color: orange;
            background-color: transparent;
        }
        .register_btn:hover {
            background-color: orange;
            color: white;
        }
        .home_title {
            align-self: center;
        }
        .container_home {
            width: 50%;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            position: relative;
            z-index: 2;
            clip-path: polygon(0 0, 100% 0, 85% 100%, 0% 100%);
        }
        .container_img {
            width: 50%;
            display: block;
            overflow: hidden;
            position: relative;
            clip-path: polygon(15% 0, 100% 0, 100% 100%, 0 100%);
        }
        .container_img img {
            width: 100%;
            height: 100%;
            object-fit: cover; 
            display: block;
        }
    </style>
</head>
<body class="bg-light">
    <div class="container_body">
                <div class="container_home">
            <h1 class="display-4 mb-3 home_title">Adota Paraná</h1>
            <p class="lead mb-1">Conectamos animais que precisam de um lar a pessoas com um grande coração.</p>
            <?php if($currentUser): ?>
                <p class="lead">Bem Vindo, você é um <?= htmlspecialchars($currentUser->role) ?></p>
            <?php endif; ?>
            <div class="mt-1">
               <?php if ($currentUser): ?>
                <a href="/admin/dashboard" class="btn register_btn btn-warning btn-ligth btn-lg px-4 gap-3 me-2">Admin</a>
                <a href="/user/dashboard" class="btn register_btn btn-warning btn-ligth btn-lg px-4 gap-3 me-2">User</a>
                <form action="/logout" method="POST" style="display:inline;">
                     <button type="submit" class="btn btn-outline-secondary btn-lg px-4">Sair</button>
                </form>
               <?php else: ?>
                <a href="/register" class="btn register_btn btn-warning btn-ligth btn-lg px-4 gap-3 me-2">Faça seu cadastro</a>
                <a href="/login" class="btn btn-outline-secondary btn-lg px-4">Faça seu login</a>
                <?php endif; ?>
            </div>
        </div>
        <div class="container_img">
            <img src="assets/images/defaults/animals.jpeg">
        </div>
    </div>
</body>
</html>
