<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adota Paraná</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">

    <div class="container d-flex flex-column align-items-center justify-content-center vh-100 text-center">
        <div class="card shadow-lg p-5" style="border-radius: 1rem; padding">
            <h1 class="display-4 mb-3">Adota Paraná</h1>
            <p class="lead mb-4">Conectamos animais que precisam de um lar a pessoas com um grande coração.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="/register" class="btn btn-primary btn-lg px-4 gap-3">Faça seu cadastro</a>
                <a href="/login" class="btn btn-outline-secondary btn-lg px-4">Faça seu login</a>
            </div>
        </div>
    </div>

</body>
</html>
